export const images = {
    logo: require("@assets/images/logo.png"),
    banner1: require("@assets/images/banner1.jpg"),
    banner2: require("@assets/images/banner2.jpg"),
    banner3: require("@assets/images/banner3.jpg"),
    banner4: require("@assets/images/banner4.jpg"),
    banner5: require("@assets/images/banner5.jpg"),
    watch1: require("@assets/images/watch1.jpg"),
    watch2: require("@assets/images/watch2.jpeg"),
    watch3: require("@assets/images/watch3.jpeg"),
    watch4: require("@assets/images/watch4.jpeg"),
    watch5: require("@assets/images/watch5.jpeg"),
    watch6: require("@assets/images/watch6.jpeg"),
    watch7: require("@assets/images/watch7.jpeg"),
    watch8: require("@assets/images/watch8.jpg"),
    express: require("@assets/images/express.png"),
    home1: require("@assets/images/home1.png"),
    home2: require("@assets/images/home2.png"),
    home3: require("@assets/images/home3.png"),
    home4: require("@assets/images/home4.png"),
    extra1: require("@assets/images/extra1.jpg"),
    extra2: require("@assets/images/extra2.png"),
    extra3: require("@assets/images/extra3.jpeg"),
    extra4: require("@assets/images/extra4.jpeg"),
    extra5: require("@assets/images/extra5.jpg"),
}

export const icons = {
    // instagram: require("@assets/icons/instagram.png"),
}