
export const images = {
  logoDark: require("@assets/images/logo-dark.png"),
  logoDefault: require("@assets/images/logo-default.png"),
  banner01: require("@assets/images/banner01.png"),
  banner02: require("@assets/images/banner02.png"),
  banner03: require("@assets/images/banner03.png"),
  banner04: require("@assets/images/banner04.png"),
  banner05: require("@assets/images/banner05.png"),
  banner06: require("@assets/images/banner06.png"),
  express: require("@assets/images/express.png"),
  image01: require("@assets/images/image01.png"),
  image02: require("@assets/images/image02.png"),
  image03: require("@assets/images/image03.png"),
  banner11: require("@assets/images/banner11.png"),
  banner12: require("@assets/images/banner12.png"),
  banner13: require("@assets/images/banner13.png"),
  banner20: require("@assets/images/banner20.png"),
  banner21: require("@assets/images/banner21.png"),
  banner22: require("@assets/images/banner22.png"),
  banner31: require("@assets/images/banner31.png"),
  banner32: require("@assets/images/banner32.png"),
  banner33: require("@assets/images/banner33.png"),
  banner34: require("@assets/images/banner34.png"),
  banner35: require("@assets/images/banner35.png"),
  banner36: require("@assets/images/banner36.png"),
  banner37: require("@assets/images/banner37.png"),

  watch1: require("@assets/images/watch1.jpg"),
  watch2: require("@assets/images/watch2.jpeg"),
  watch3: require("@assets/images/watch3.jpeg"),
  watch4: require("@assets/images/watch4.jpeg"),
  watch5: require("@assets/images/watch5.jpeg"),
  watch6: require("@assets/images/watch6.jpeg"),
  watch7: require("@assets/images/watch7.jpeg"),
  watch8: require("@assets/images/watch8.jpg"),

  brand01: require("@assets/images/brand01.png"),
  brand02: require("@assets/images/brand02.png"),
  brand03: require("@assets/images/brand03.png"),
  brand04: require("@assets/images/brand04.png"),
  brand05: require("@assets/images/brand05.png"),
  brand06: require("@assets/images/brand06.png"),
  brand07: require("@assets/images/brand07.png"),
  brand08: require("@assets/images/brand08.png"),
  brand09: require("@assets/images/brand09.png"),

  home1: require("@assets/images/home1.png"),
  home2: require("@assets/images/home2.png"),
  home3: require("@assets/images/home3.png"),
  home4: require("@assets/images/home4.png"),
  extra1: require("@assets/images/extra1.jpg"),
  extra2: require("@assets/images/extra2.png"),
  extra3: require("@assets/images/extra3.jpeg"),
  extra4: require("@assets/images/extra4.jpeg"),
  extra5: require("@assets/images/extra5.jpg"),

  orders: require("@assets/images/orders.png"),
  returns: require("@assets/images/returns.png"),
  request: require("@assets/images/request.png"),
  credit: require("@assets/images/credit.png"),
}

export const icons = {
  saudiArabia: require("@assets/icons/saudi-arabia.png"),
  unitedArabEmirates: require("@assets/icons/united-arab-emirates.png"),
  egypt: require("@assets/icons/egypt.png"),
}

export const dummy = {
  banners: [
    { image: images.banner01 },
    { image: images.banner02 },
    { image: images.banner03 },
    { image: images.banner04 },
    { image: images.banner05 },
    { image: images.banner06 },
  ],
  banners2: [
    { image: images.banner11 },
    { image: images.banner12 },
    { image: images.banner13 },
  ],
  banners3: [
    { image: images.banner31 },
    { image: images.banner32 },
  ],
  categories: [
    { category: "SOPRTS &\nOUTDOORS", image: "https://i.pinimg.com/originals/e0/92/59/e09259864c404ffe4fa1850b2908556b.jpg" },
    { category: "ELECTRONICS", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT3A8uLLQLuMkw9FiPduRy2EIrzGn392BLEqg&usqp=CAU" },
    { category: "FASHION", image: "https://i.pinimg.com/originals/0a/4b/37/0a4b37314b1b635598998d73037957f0.jpg" },
    { category: "LAPTOPS", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ5bLKs8isRS9PZ0ZWVtVCfc7_dupL4GVRYwg&usqp=CAU" },
    { category: "STATIONERY", image: "https://i.pinimg.com/originals/60/5d/24/605d242879debfec268d407bd541491f.jpg" },
    { category: "TOYS & GAMES", image: "https://i.pinimg.com/originals/60/5d/24/605d242879debfec268d407bd541491f.jpg" },
    { category: "GAMING", image: "https://i.pinimg.com/originals/a5/5f/b0/a55fb0a2d7ab1ab7f4c17e5845776135.jpg" },
    { category: "BEAUTY", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSk0ySWOZiBVZT5_WGAaoz8DpU6QLZsfqbuJg&usqp=CAU" },
    { category: "MOBILES", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQozRVYMlxlaFgqGwQbNAP0h-jf6n_7c1VYvA&usqp=CAU" },
    { category: "BABY\nESSENTIALS", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQJB9U0oufnXHcLyVmOjDQ-iDUA1UiOw_ByIQ&usqp=CAU" },
  ],
  categories2: [
    { category: "Backpacks", image: "https://i.pinimg.com/originals/e0/92/59/e09259864c404ffe4fa1850b2908556b.jpg" },
    { category: "Laptops", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT3A8uLLQLuMkw9FiPduRy2EIrzGn392BLEqg&usqp=CAU" },
    { category: "Stationery", image: "https://i.pinimg.com/originals/0a/4b/37/0a4b37314b1b635598998d73037957f0.jpg" },
    { category: "Headphones", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ5bLKs8isRS9PZ0ZWVtVCfc7_dupL4GVRYwg&usqp=CAU" },
    { category: "Mask & sanitizers", image: "https://i.pinimg.com/originals/60/5d/24/605d242879debfec268d407bd541491f.jpg" },
    { category: "Books", image: "https://i.pinimg.com/originals/60/5d/24/605d242879debfec268d407bd541491f.jpg" },
    { category: "Lunch boxes", image: "https://i.pinimg.com/originals/a5/5f/b0/a55fb0a2d7ab1ab7f4c17e5845776135.jpg" },
    { category: "Backpack sets", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSk0ySWOZiBVZT5_WGAaoz8DpU6QLZsfqbuJg&usqp=CAU" },
    { category: "Tablets", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQozRVYMlxlaFgqGwQbNAP0h-jf6n_7c1VYvA&usqp=CAU" },
  ],
  categories3: [
    { category: "Trollery backpacks", image: "https://i.pinimg.com/originals/e0/92/59/e09259864c404ffe4fa1850b2908556b.jpg" },
    { category: "Cartoon backpacks", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT3A8uLLQLuMkw9FiPduRy2EIrzGn392BLEqg&usqp=CAU" },
    { category: "Sports backpacks", image: "https://i.pinimg.com/originals/0a/4b/37/0a4b37314b1b635598998d73037957f0.jpg" },
    { category: "Fashion backpacks", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ5bLKs8isRS9PZ0ZWVtVCfc7_dupL4GVRYwg&usqp=CAU" },
    { category: "Laptop\nbags", image: "https://i.pinimg.com/originals/60/5d/24/605d242879debfec268d407bd541491f.jpg" },
  ],
  categories4: [
    { category: "3-8\nyears", image: "https://i.pinimg.com/originals/a5/5f/b0/a55fb0a2d7ab1ab7f4c17e5845776135.jpg" },
    { category: "9-13\nyears", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSk0ySWOZiBVZT5_WGAaoz8DpU6QLZsfqbuJg&usqp=CAU" },
    { category: "14+\nyears", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQozRVYMlxlaFgqGwQbNAP0h-jf6n_7c1VYvA&usqp=CAU" },
  ],
  categories5: [
    { category: "Notebooks", image: "https://i.pinimg.com/originals/e0/92/59/e09259864c404ffe4fa1850b2908556b.jpg" },
    { category: "Pens, pencils & highlighters", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT3A8uLLQLuMkw9FiPduRy2EIrzGn392BLEqg&usqp=CAU" },
    { category: "Printers & accessories", image: "https://i.pinimg.com/originals/0a/4b/37/0a4b37314b1b635598998d73037957f0.jpg" },
    { category: "Calculators", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ5bLKs8isRS9PZ0ZWVtVCfc7_dupL4GVRYwg&usqp=CAU" },
    { category: "Children's books", image: "https://i.pinimg.com/originals/60/5d/24/605d242879debfec268d407bd541491f.jpg" },
    { category: "Art & craft supplies", image: "https://i.pinimg.com/originals/a5/5f/b0/a55fb0a2d7ab1ab7f4c17e5845776135.jpg" },
  ],
  recommends: [
    { image: images.watch1, description: "Geneva Women's Water Resistant Leather Ana...", price: '10.90', express: true },
    { image: images.watch2, description: "Geneva Women's Water Resistant Leather Ana...", price: '200.30', express: true, price2: '749.00', percent: '16', saving: '10' },
    { image: images.watch3, description: "Geneva Women's Water Resistant Leather Ana...", price: '35.40', express: true, price2: '749.00', percent: '20', saving: '10' },
    { image: images.watch4, description: "Geneva Women's Water Resistant Leather Ana...", price: '234.00', express: true },
    { image: images.watch5, description: "Geneva Women's Water Resistant Leather Ana...", price: '123.90', express: true, price2: '749.00', percent: '40', saving: '10' },
    { image: images.watch6, description: "Geneva Women's Water Resistant Leather Ana...", price: '534.90', express: true },
    { image: images.watch7, description: "Geneva Women's Water Resistant Leather Ana...", price: '43.90', express: true, price2: '749.00', percent: '90', saving: '10' }
  ],
  brands: [
    { image: images.brand01 },
    { image: images.brand02 },
    { image: images.brand03 },
    { image: images.brand04 },
    { image: images.brand05 },
    { image: images.brand06 },
    { image: images.brand07 },
    { image: images.brand08 },
    { image: images.brand09 },
  ],
  data1: [
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS6_uPKQFZ2AzsbChsoFr7r6IAi-JsG_kcetQ&usqp=CAU", title: "Appllances", description: "Cool down with ACs, fants,\nwater coolers & more" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTVWjOESWL2ILZmVmKa16Maab7B6YHP7BrmBQ&usqp=CAU", title: "Water Play", description: "Fun times in the sun with\nswimming pools & more" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQcnl7267l13vpPN2i345YzUQRDXnZybZ2Daw&usqp=CAU", title: "Summer\nfashion trends", description: "Stay cool with light fabrics\n& colourful hues" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSK8VuDRXcBLyL2Fp0v3rM2HM5pBE98eSO5BA&usqp=CAU", title: "Beauty &\npersonal care", description: "Beauty & hydrate\nyour skin" },
  ],
  data2: [
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTo-DIOwvdrmHBHZeSHvBk-4Drlv3qydneSUw&usqp=CAU", title: "Mobiles" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTK4NnhxJlDlFigT2fId9AwB-lNjELeRmMPbQ&usqp=CAU", title: "Tablets" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSQvo8VJdtjm4yFq-hiUJxMIsJr7W5PgFWZiw&usqp=CAU", title: "Accessirues" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSK8VuDRXcBLyL2Fp0v3rM2HM5pBE98eSO5BA&usqp=CAU", title: "Audio & Video" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTpqsQSPaGZR8oIbECTHkXoiENlQA9D93ydzA&usqp=CAU", title: "Computers & Networking" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQwuMc1KCVp61MEHu8j3s5eY-QNekY8zRIZdA&usqp=CAU", title: "Camera" },
  ],
  data3: [
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRFDtVVkOZeBd-Vpy5HZkelobBWxtf636GXZA&usqp=CAU", title: "Repaired, repurposed, rebuilt items at amazing prices" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS804W2nRYa4rDzASThTPn6E-7Sz32XUWu_Yg&usqp=CAU", title: "Original items, thoroughly tested and like new -for you!" },
  ],
  data4: [
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSo7Lk25xQuOZRTzFlDsVfpW1KvkBpcFitCQQ&usqp=CAU", title: "Applications" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTy2FvkBpDwNRfGJ8TUiSddT5Fm_eLJHXg75Q&usqp=CAU", title: "Home & Kitchen" },
  ],
  data5: [
    { image: "https://png.pngtree.com/png-clipart/20190120/ourmid/pngtree-beauty-europe-female-model-european-and-american-model-flat-model-clothing-png-image_492996.jpg", title: "Kitchen & Dining" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR2jqdVHrC4Abaz5zi-LbsFyWhV7-07G6jtgQ&usqp=CAU", title: "Home Applications" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQE-7JXf6QBCPPHoLZ2qm_YB2DTMx94lTGc6g&usqp=CAU", title: "Kitchen Appliances" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSSSFKC7rWwWx4v7pfW6uEOwuxB7m-B4_14pQ&usqp=CAU", title: "Home Decor" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRtaVLvu3FLvqrz8NXqZzmd8_BQp4x99_jvxw&usqp=CAU", title: "Bedding" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSFsLstMTVnKIkj0ZxN_GWf-aYcuAHLLKcB9g&usqp=CAU", title: "Bath" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQkGxw0f88cpPUJLrBr4hKJ00fG3AxluoI6LQ&usqp=CAU", title: "Tools & Home Improvement" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQa6zp9h0mOfDsnO1kDLf3THgr7lH-R_Kt_ZA&usqp=CAU", title: "Storage & Organization" },
    { image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS-GarYbJRYqV-8ZT6gzI81peBdP0OJZ67AXA&usqp=CAU", title: "Furniture" },
  ],

  categoryList: [
    { categoryName: "Just for you" },
    { categoryName: "Mobiles & Accessories" },
    { categoryName: "Electronics" },
    { categoryName: "TVs & Appliances" },
    { categoryName: "Women's Fashion" },
    { categoryName: "Men's Fashion" },
    { categoryName: "Home & Kitchen" },
    { categoryName: "Watches, Bags & Accessories" },
    { categoryName: "Fragrance" },
    { categoryName: "Beauty & Personal Care" },
    { categoryName: "Kids, Baby Products & Toy" },
    { categoryName: "Sports & Fitness" },
    { categoryName: "Office Supplies, Books & Media" },
    { categoryName: "Automotive" }
  ],

  details: [
    {
      id: 1, type: 'Elago', title: 'Scratch Resistant Silicon case For Apple AirPods Dark Grey', price: '44.00',
      time: '23 hrs 28 mins', date: 'Mon, Aug 31',
      sold: 'Gulf-Click', image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR2jqdVHrC4Abaz5zi-LbsFyWhV7-07G6jtgQ&usqp=CAU"
    },
    {
      id: 1, type: 'Elago', title: 'Scratch Resistant Silicon case For Apple AirPods Dark Grey', price: '44.00',
      time: '23 hrs 28 mins', date: 'Mon, Aug 31',
      sold: 'Gulf-Click', image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR2jqdVHrC4Abaz5zi-LbsFyWhV7-07G6jtgQ&usqp=CAU"
    }
  ],
  detail: {
    images: [
      {image: images.watch1},
      {image: images.watch2},
      {image: images.watch3},
      {image: images.watch4},
      {image: images.watch5},
    ],
    type: 'GUANQIN',
    title: 'Mens Waters Resistant Stainless Steel Chronograph Watch SW0029',
    price: '74.15',
    price2: '169.00',
    percent: '56',
    time: '4 hrs 51 mins',
    date: 'Tomorrow, Aug 27',
  },

  mobiles1: [
    { image: images.home1, title: "Under SAR 499" },
    { image: images.home2, title: "500-999" },
    { image: images.watch3, title: "1000-1999" },
    { image: images.watch4, title: "2000-2999" },
    { image: images.watch5, title: "3000-3999" },
    { image: images.watch6, title: "4000 & More" }
  ],
}