require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# Override Firebase SDK Version
$FirebaseSDKVersion = '6.28.0'
$RNFirebaseAsStaticFramework = true

platform :ios, '10.0'

target 'Paksa' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  target 'PaksaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Paksa-tvOS' do
  # Pods for Paksa-tvOS
  target 'Paksa-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
